// frontend/src/App.svelte
<script lang="ts">
  import { GetRandomImageUrl } from "../wailsjs/go/main/App.js";
  import { GetBreedList } from "../wailsjs/go/main/App.js";
  import { GetImageUrlsByBreed } from "../wailsjs/go/main/App.js";

  let randomImageUrl = "";
  let breeds = [];
  let photos = [];
  let selectedBreed: string;
  let showRandomPhoto = false;
  let showBreedPhotos = false;

  function init() {
    getBreedList();
  }

  init();

  function getRandomImageUrl() {
    showRandomPhoto = false;
    showBreedPhotos = false;
    GetRandomImageUrl().then((result) => (randomImageUrl = result));
    showRandomPhoto = true;
  }

  function getBreedList() {
    GetBreedList().then((result) => (breeds = result));
  }

  function getImageUrlsByBreed() {
    init();
    showRandomPhoto = false;
    showBreedPhotos = false;
    GetImageUrlsByBreed(selectedBreed).then((result) => (photos = result));
    showBreedPhotos = true;
  }
</script>

<main>
  <h3>Dogs API</h3>
  <div>
    <button class="btn" on:click={getRandomImageUrl}>
      Fetch a dog randomly
    </button>
    Click on down arrow to select a breed
    <select bind:value={selectedBreed}>
      {#each breeds as breed}
        <option value={breed}>
          {breed}
        </option>
      {/each}
    </select>
    <button class="btn" on:click={getImageUrlsByBreed}>
      Fetch by this breed
    </button>
  </div>
  <br />
  {#if showRandomPhoto}
    <img id="random-photo" src={randomImageUrl} alt="No dog found" />
  {/if}
  {#if showBreedPhotos}
    {#each photos as photo}
      <img id="breed-photos" src={photo} alt="No dog found" />
    {/each}
  {/if}
</main>

<style>
  #random-photo {
    width: 600px;
    height: auto;
  }

  #breed-photos {
    width: 300px;
    height: auto;
  }

  .btn:focus {
    border-width: 3px;
  }
</style>

// frontend/src/App.tsx
import { useEffect, useState, ChangeEvent } from "react";
import "./App.css";
import {
  GetBreedList,
  GetImageUrlsByBreed,
  GetRandomImageUrl,
} from "../wailsjs/go/main/App";

function App() {
  const [randomImageUrl, setRandomImageUrl] = useState("");
  const [breeds, setBreeds] = useState<string[]>([]);
  const [photos, setPhotos] = useState<string[]>([]);

  const [selectedBreed, setSelectedBreed] = useState<string>("");
  const updateSelectedBreed = (event: ChangeEvent<HTMLSelectElement>) => {
    setSelectedBreed(event.target.value);
  };

  const [showRandomPhoto, setShowRandomPhoto] = useState(false);
  const [showBreedPhotos, setShowBreedPhotos] = useState(false);

  useEffect(() => {
    getBreedList();
  }, []);

  function getRandomImageUrl() {
    setShowRandomPhoto(false);
    setShowBreedPhotos(false);
    GetRandomImageUrl().then((result) => setRandomImageUrl(result));
    setShowRandomPhoto(true);
  }

  function getBreedList() {
    GetBreedList().then((result) => setBreeds(result));
  }

  function getImageUrlsByBreed() {
    setShowRandomPhoto(false);
    setShowBreedPhotos(false);
    GetImageUrlsByBreed(selectedBreed).then((result) => setPhotos(result));
    setShowBreedPhotos(true);
  }

  return (
    <div id="App">
      <div>
        <button className="btn" onClick={getRandomImageUrl}>
          Fetch a dog randomly
        </button>
        <p>Click on down arrow to select a breed</p>
        <select
          title="select-breed"
          value={selectedBreed}
          onChange={updateSelectedBreed}
        >
          {breeds?.map((breed, i) => (
            <option key={i} value={breed}>
              {breed}
            </option>
          ))}
        </select>
        <button className="btn" onClick={getImageUrlsByBreed}>
          Fetch by this breed
        </button>
      </div>

      {showRandomPhoto && (
        <img id="random-photo" src={randomImageUrl} alt="No dog found" />
      )}

      {showBreedPhotos &&
        photos?.map((photo, i) => (
          <img key={i} id="breed-photos" src={photo} alt="No dog found" />
        ))}
    </div>
  );
}

export default App;
